const allCodes: Record<string, string> = {
  Backspace: 'Backspace',
  Tab: 'Tab',
  Enter: 'Enter',
  ShiftLeft: 'Shift',
  ControlLeft: 'Control',
  ShiftRight: 'Shift',
  ControlRight: 'Control',
  AltLeft: 'Alt',
  AltRight: 'Alt',
  CapsLock: 'CapsLock',
  Escape: 'Escape',
  Space: 'Space',
  ArrowLeft: 'Left',
  ArrowUp: 'Up',
  ArrowRight: 'Right',
  ArrowDown: 'Down',
  Delete: 'Delete',
  Digit0: '0',
  Digit1: '1',
  Digit2: '2',
  Digit3: '3',
  Digit4: '4',
  Digit5: '5',
  Digit6: '6',
  Digit7: '7',
  Digit8: '8',
  Digit9: '9',
  KeyA: 'a',
  KeyB: 'b',
  KeyC: 'c',
  KeyD: 'd',
  KeyE: 'e',
  KeyF: 'f',
  KeyG: 'g',
  KeyH: 'h',
  KeyI: 'i',
  KeyJ: 'j',
  KeyK: 'k',
  KeyL: 'l',
  KeyM: 'm',
  KeyN: 'n',
  KeyO: 'o',
  KeyP: 'p',
  KeyQ: 'q',
  KeyR: 'r',
  KeyS: 's',
  KeyT: 't',
  KeyU: 'u',
  KeyV: 'v',
  KeyW: 'w',
  KeyX: 'x',
  KeyY: 'y',
  KeyZ: 'z',
  Semicolon: ';',
  Quote: "'",
  Backslash: '\\',
  Comma: ',',
  Period: '.',
  Slash: '/',
  Backquote: '`',
  Minus: '-',
  Equal: '=',
  // Backspace: 8,
  // Tab: 9,
  // Enter: 13,
  // Shift: 16,
  // Ctrl: 17,
  // Alt: 18,
  // CapsLock: 20,
  // Space: 32,
  // Left: 37,
  // Up: 38,
  // Right: 39,
  // Down: 40,
  // Delete: 46,
  // '`': 192,
  // '1': 49,
  // '2': 50,
  // '3': 51,
  // '4': 52,
  // '5': 53,
  // '6': 54,
  // '7': 55,
  // '8': 56,
  // '9': 57,
  // '0': 48,
  // '-': 189,
  // '=': 187,
  // a: 65,
  // b: 66,
  // c: 67,
  // d: 68,
  // e: 69,
  // f: 70,
  // g: 71,
  // h: 72,
  // i: 73,
  // j: 74,
  // k: 75,
  // l: 76,
  // m: 77,
  // n: 78,
  // o: 79,
  // p: 80,
  // q: 81,
  // r: 82,
  // s: 83,
  // t: 84,
  // u: 85,
  // v: 86,
  // w: 87,
  // x: 88,
  // y: 89,
  // z: 90,
  // leftwindowkey: 91,
  // rightwindowkey: 92,
  // selectkey: 93,
  // numpad0: 96,
  // numpad1: 97,
  // numpad2: 98,
  // numpad3: 99,
  // numpad4: 100,
  // numpad5: 101,
  // numpad6: 102,
  // numpad7: 103,
  // numpad8: 104,
  // numpad9: 105,
  // multiply: 106,
  // add: 107,
  // subtract: 109,
  // decimalpoint: 110,
  // divide: 111,
  // f1: 112,
  // f2: 113,
  // f3: 114,
  // f4: 115,
  // f5: 116,
  // f6: 117,
  // f7: 118,
  // f8: 119,
  // f9: 120,
  // f10: 121,
  // f11: 122,
  // f12: 123,
  // numlock: 144,
  // scrolllock: 145,
  // semicolon: 186,
  // equalsign: 187,
  // comma: 188,
  // dash: 189,
  // period: 190,
  // forwardslash: 191,
  // graveaccent: 192,
  // openbracket: 219,
  // backslash: 220,
  // closebracket: 221,
  // singlequote: 222,
};

const func = {
  Backspace: 'Backspace',
  Tab: 'Tab',
  Enter: 'Enter',
  ShiftLeft: 'Shift',
  ShiftRight: 'Shift',
  ControlLeft: 'Control',
  ControlRight: 'Control',
  AltLeft: 'Alt',
  AltRight: 'Alt',
  CapsLock: 'CapsLock',
  Escape: 'Escape',
  Space: 'Space',
  ArrowLeft: 'Left',
  ArrowUp: 'Up',
  ArrowRight: 'Right',
  ArrowDown: 'Down',
  Delete: 'Delete',
  // Meta: 'Win',
};

const nums = {
  Backquote: `\``,
  Digit0: '0',
  Digit1: '1',
  Digit2: '2',
  Digit3: '3',
  Digit4: '4',
  Digit5: '5',
  Digit6: '6',
  Digit7: '7',
  Digit8: '8',
  Digit9: '9',
  Minus: '-',
  Equal: '=',
};

const numsShift = {
  Backquote: '~',
  Digit0: '!',
  Digit1: '@',
  Digit2: '#',
  Digit3: '$',
  Digit4: '%',
  Digit5: '^',
  Digit6: '&',
  Digit7: '*',
  Digit8: '(',
  Digit9: ')',
  Minus: '_',
  Equal: '+',
};

const alpabet = {
  KeyA: 'a',
  KeyB: 'b',
  KeyC: 'c',
  KeyD: 'd',
  KeyE: 'e',
  KeyF: 'f',
  KeyG: 'g',
  KeyH: 'h',
  KeyI: 'i',
  KeyJ: 'j',
  KeyK: 'k',
  KeyL: 'l',
  KeyM: 'm',
  KeyN: 'n',
  KeyO: 'o',
  KeyP: 'p',
  KeyQ: 'q',
  KeyR: 'r',
  KeyS: 's',
  KeyT: 't',
  KeyU: 'u',
  KeyV: 'v',
  KeyW: 'w',
  KeyX: 'x',
  KeyY: 'y',
  KeyZ: 'z',
  Semicolon: ';',
  Quote: "'",
  Backslash: '\\',
  Comma: ',',
  Period: '.',
  Slash: '/',
  Backquote: '`',
};
const alpabetAlt = {
  KeyA: 'ф',
  KeyB: 'и',
  KeyC: 'с',
  KeyD: 'в',
  KeyE: 'у',
  KeyF: 'а',
  KeyG: 'п',
  KeyH: 'р',
  KeyI: 'ш',
  KeyJ: 'о',
  KeyK: 'л',
  KeyL: 'д',
  KeyM: 'ь',
  KeyN: 'т',
  KeyO: 'щ',
  KeyP: 'з',
  KeyQ: 'й',
  KeyR: 'к',
  KeyS: 'ы',
  KeyT: 'е',
  KeyU: 'г',
  KeyV: 'м',
  KeyW: 'ц',
  KeyX: 'ч',
  KeyY: 'н',
  KeyZ: 'я',
  Semicolon: 'ж',
  Quote: 'б',
  Backslash: 'ю',
  Comma: 'х',
  Period: 'ъ',
  Slash: 'э',
  Backquote: 'ё',
};

// const arr = {
// Backspace: 'Backspace',
// Tab: 'Tab',
// Enter: 'Enter',
// ShiftLeft: 'Shift',
// ShiftRight: 'Shift',
// ControlLeft: 'Control',
// ControlRight: 'Control',
// AltLeft: 'Alt',
// AltRight: 'Alt',
// CapsLock: 'CapsLock',
// Escape: 'Escape',
// Space: 'Space',
// ArrowLeft: 'Left',
// ArrowUp: 'Up',
// ArrowRight: 'Right',
// ArrowDown: 'Down',
// Delete: 'Delete',
// Digit0: '0',
// Digit1: '1',
// Digit2: '2',
// Digit3: '3',
// Digit4: '4',
// Digit5: '5',
// Digit6: '6',
// Digit7: '7',
// Digit8: '8',
// Digit9: '9',
// KeyA: 'a',
// KeyB: 'b',
// KeyC: 'c',
// KeyD: 'd',
// KeyE: 'e',
// KeyF: 'f',
// KeyG: 'g',
// KeyH: 'h',
// KeyI: 'i',
// KeyJ: 'j',
// KeyK: 'k',
// KeyL: 'l',
// KeyM: 'm',
// KeyN: 'n',
// KeyO: 'o',
// KeyP: 'p',
// KeyQ: 'q',
// KeyR: 'r',
// KeyS: 's',
// KeyT: 't',
// KeyU: 'u',
// KeyV: 'v',
// KeyW: 'w',
// KeyX: 'x',
// KeyY: 'y',
// Key: 'z',
// Semicolon: ';',
// Quote: "'",
// Backslash: '\\',
// Comma: ',',
// Period: '.',
// Slash: '/',
// Backquote: '`',
// };

export { alpabet, nums, func, alpabetAlt, allCodes, numsShift };
